apiVersion: apps/v1
kind: Deployment
metadata:
  name: koala-command-handler
spec:
    replicas: 1
    selector:
        matchLabels:
        app: koala-command-handler-service
    template:
        metadata:
        labels:
            app: koala-command-handler-service
        spec:
        containers:
        - name: koala-command-handler-service
          image: koala-command-handler-service
          env:
            - name: DOTNET_ENVIRONMENT
              value: "Production"