apiVersion: v1
kind: Service
metadata:
  name: koala-command-handler
spec:
    selector:
        app: koala-command-handler
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: koala-command-handler
spec:
    replicas: 1
    selector:
        matchLabels:
          app: koala-command-handler
    template:
        metadata:
          labels:
            app: koala-command-handler
        spec:
          containers:
          - name: koala-command-handler
            image: koala-command-handler
            ports:
              - containerPort: 8080
            env:
              - name: ASPNETCORE_ENVIRONMENT
                value: "Production"