apiVersion: v1
kind: Service
metadata:
  name: koala-command-handler
spec:
    selector:
        app: koala-command-handler
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: koala-command-handler
spec:
    replicas: 1
    selector:
        matchLabels:
        app: koala-command-handler
    template:
        spec:
        containers:
        - name: koala-command-handler
          image: koala-command-handler
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
  